--total revenue generated by 
select gender, sum(purchase_amount) as total_revenue 
from customer 
group by gender;

--customers who have applied discount but still spended more than average amount
select customer_id, purchase_amount from customer
where discount_applied='Yes' and
purchase_amount > 
(select avg(purchase_amount) from customer);

--top 5 products with highest average review rating
select item_purchased, round(avg(review_rating)::numeric,2) as average_review_rating
from customer
group by 1
order by 2 desc
limit 5;

--compare average purchase amount between express and standard shipping
select round(avg(purchase_amount),2) as average_purchase_amount, shipping_type from customer
where shipping_type in ('Standard','Express')
group by 2;

--do subscribed customers spend more?
select subscription_status, sum(purchase_amount), count(customer_id) from customer
group by 1;

--top 5 products with highest percentage of purchses with discount applied
select item_purchased,
(sum(case when discount_applied='Yes' then 1 else 0 end)*100/count(*)) as discount_rate
from customer
group by 1
order by discount_rate desc
limit 5;

--top 3 most purchased products in each category
select item_purchased, category, total_purchase from
(select item_purchased, category, count(customer_id) as total_purchase,
row_number() over (partition by category order by count(customer_id) desc) as rn
from customer
group by 1,2)
where rn<=3;